# Generated by Django 4.1.5 on 2023-01-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
