# Generated by Django 4.1.7 on 2023-03-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='confirmation_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
